### ISSUE TITLE
Need to be able to remove metadata with specific values

### ISSUE THREAD

**Issue by ggailey777** [craigshoemaker/tensies#4]
Because of the new docfx.json mandates, we need to be able to remove metadata only when it has a specific value, for example, when `author` or `ms.author` is the same as the default set in the docfx.json file for the folder.

**Comment by craigshoemaker** [comment]
Let's talk about where the relative path of the *docfx.json* file is in relation to the content and it's schema. Once I have that info, it'll be easy to read from the file and then handle the removals.

**Comment by craigshoemaker** [comment]
Closed by e7f88ada2e4237dd2b8487fdfd878c073640ed9b
